open module com.mastfrog.acteur.tutorial.v4 {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.tutorial.v4;

    // derived from com.google.guava/guava-31.1-jre in com/google/guava/guava/31.1-jre/guava-31.1-jre.pom
    requires transitive com.google.guava.guava;
    requires transitive com.mastfrog.acteur.headers;
    requires transitive com.mastfrog.acteur.mongo;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.jackson;
    requires transitive com.mastfrog.netty.http.test.harness;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.mongodb/mongo-java-driver-3.12.11 in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires transitive org.mongodb.mongo.java.driver;

}
