// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.tutorial.v3 {
    exports com.mastfrog.acteur.tutorial.v1;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

    // Sibling com.mastfrog/acteur-mongo-3.0.0-dev
    requires com.mastfrog.acteur.mongo;

    // derived from org.javassist/javassist-3.28.0-GA in org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.pom
    requires transitive javassist.3.28.0.GA;

    // derived from org.mongodb/mongo-java-driver-0.0.0-? in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires transitive mongo.java.driver.3.12.11;

}
