open module com.mastfrog.acteur.tutorial.v2 {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.tutorial.v1;
    requires transitive com.mastfrog.acteur.mongo;

    // derived from org.javassist/javassist-3.28.0-GA in org/javassist/javassist/3.28.0-GA/javassist-3.28.0-GA.pom
    requires transitive org.javassist.javassist;

    // derived from org.mongodb/mongo-java-driver-3.12.11 in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires transitive org.mongodb.mongo.java.driver;

}
