// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.acteur.tutorial.v1 {
    exports com.mastfrog.acteur.tutorial.v1;

    // Transitive detected by source scan
    requires com.mastfrog.acteur.deprecated;

}
